
only_print_a_fckn_number_man: only_print_a_fckn_number_man.o
	ld -o only_print_a_fckn_number_man only_print_a_fckn_number_man.o
only_print_a_fckn_number_man.o:
	nasm -f elf64 -g -F dwarf only_print_a_fckn_number_man.asm 

clean:
	rm -f only_print_a_fckn_number_man
	rm -f only_print_a_fckn_number_man.o


